steps:

    - label: ':docker: :hammer:'
      command: |
          make docker-build
          make ecr-login
          DOCKER_TAG=latest \
          make docker-push
          # push bk no
          DOCKER_TAG=${BUILDKITE_BUILD_NUMBER} \
          make docker-push
          # push git hash
          DOCKER_TAG=${BUILDKITE_COMMIT} \
          make docker-push
      agents:
          queue: qa

    - wait

    - label: ':package:'
      command: |
          DOCKER_IMAGE=$(make ecr-uri):${BUILDKITE_BUILD_NUMBER} \
          make ecs-createtask
      agents:
          queue: qa

    - wait

    - label: ':mag_right:'
      command: |
          make ecs-getrevision | buildkite-agent meta-data set "${TARGET_ENV}ecstaskrev"
          make ecs-getcount | buildkite-agent meta-data set "${TARGET_ENV}ecsservicecount"
      env:
          TARGET_ENV: qa
      agents:
          queue: qa
    - label: ':mag_right:'
      command: |
          make ecs-getrevision | buildkite-agent meta-data set "${TARGET_ENV}ecstaskrev"
          make ecs-getcount | buildkite-agent meta-data set "${TARGET_ENV}ecsservicecount"
      env:
          TARGET_ENV: perf
      agents:
          queue: qa
    - label: ':mag_right:'
      command: |
          make ecs-getrevision | buildkite-agent meta-data set "${TARGET_ENV}ecstaskrev"
          make ecs-getcount | buildkite-agent meta-data set "${TARGET_ENV}ecsservicecount"
      env:
          TARGET_ENV: ete
      agents:
          queue: qa

    - wait

    - label: ':ecs: QA :rocket:'
      command: |
          SVCNT=$(buildkite-agent meta-data get "${TARGET_ENV}ecsservicecount") \
          TASKREV=$(buildkite-agent meta-data get "${TARGET_ENV}ecstaskrev") \
          make ecs-updateservice
      env:
          TARGET_ENV: qa
      agents:
          queue: qa

    - wait

    - label: ':ecs: PERF :rocket:'
      command: |
          SVCNT=$(buildkite-agent meta-data get "${TARGET_ENV}ecsservicecount") \
          TASKREV=$(buildkite-agent meta-data get "${TARGET_ENV}ecstaskrev") \
          make ecs-updateservice
      env:
          TARGET_ENV: perf
      agents:
          queue: qa

    - block: ":lock:"

    - label: ':ecs: ETE :rocket:'
      command: |
          SVCNT=$(buildkite-agent meta-data get "${TARGET_ENV}ecsservicecount") \
          TASKREV=$(buildkite-agent meta-data get "${TARGET_ENV}ecstaskrev") \
          make ecs-updateservice
      env:
          TARGET_ENV: ete
      agents:
          queue: qa



env:
    SERVICE_NAME: smctest
